version: '3.8'

services:
  # --- Go Application ---
  api-server:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: nanolink-api
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongo:27017
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - redis
      - mongo
      - kafka

  analytics-worker:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: nanolink-worker
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MONGO_URI=mongodb://mongo:27017  # <--- ADD THIS (Points to the 'mongo' container)
    depends_on:
      - kafka
      - mongo                            # <--- Good practice to wait for mongo too
    command: ["./analytics-worker"]

  # --- Infrastructure ---
  redis:
    image: redis:7-alpine
    container_name: nanolink-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    container_name: nanolink-mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: nanolink-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: nanolink-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
